language: node_js

node_js:
  - "node"

addons:
  firefox: "61.0.2"

git:
  depth: 3

before_deploy: scripts/travis-before_deploy.sh

deploy:
  provider: script
  skip_cleanup: true
  script: /tmp/deploy/travis-deploy.sh
  on:
    branch: master

script:
  - npm run regression
  - grep "before Rejected promise returned by test" ./logs/* -C 500
  - grep "Failed to decode response from marionette" ./logs/* -C 500