language: node_js

node_js:
  - "8" # LTS

addons:
  firefox: "60.0.2"

git:
  depth: 3

script: npm run lint && npm run vnu-jar && ava -c 2 test/tests

before_deploy: scripts/travis-before_deploy.sh

deploy:
  provider: script
  skip_cleanup: true
  script: /tmp/deploy/travis-deploy.sh
  on:
    branch: master

cache:
  directories:
    - "node_modules"
