language: node_js

node_js:
  - "node"

addons:
  firefox: "60.0.2"

git:
  depth: 3

before_deploy: scripts/travis-before_deploy.sh

deploy:
  provider: script
  skip_cleanup: true
  script: /tmp/deploy/travis-deploy.sh
  on:
    branch: master
